//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdHocProject
    {
        public int AHID { get; set; }
        public Nullable<double> RevenueID { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string Comments { get; set; }
        public string GlobalCISOBTLead { get; set; }
        public string RegionalCISOBTLead { get; set; }
        public string LocalDigitalOBTLead { get; set; }
        public string GlobalCISPortraitLead { get; set; }
        public string RegionalCISPortraitLead { get; set; }
        public string GlobalCISHRFeedSpecialist { get; set; }
        public string GDS { get; set; }
        public Nullable<double> ComplexityScore { get; set; }
        public string ActivityType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string ProjectStatus { get; set; }
        public string GlobalDQSLead { get; set; }
    }
}
