//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignePerson
    {
        public int AssigneID { get; set; }
        public string Task_Title { get; set; }
        public Nullable<System.DateTime> Task_Start_Date { get; set; }
        public Nullable<System.DateTime> Task_Due_Date { get; set; }
        public string Milestone_Title { get; set; }
        public string Workspace_Title { get; set; }
        public string Task__Assigned_Role__Name { get; set; }
        public string Task__Assignee__Reports_to__Full_Name { get; set; }
        public string Task__Task_Type { get; set; }
        public string Task__Task_Record_ID_Key { get; set; }
        public string Workspace__ELT_Overall_Status { get; set; }
        public string Workspace__ELT_Overall_Comments { get; set; }
        public string Workspace__Project_Level { get; set; }
        public string Workspace__Project_Owner__Full_Name { get; set; }
        public Nullable<double> Milestone__CRM_Revenue_ID__ { get; set; }
        public string Milestone__Assignee__Reports_to__Full_Name { get; set; }
        public string Milestone__Country { get; set; }
        public string Milestone__Project_Status { get; set; }
        public string Milestone__Country_Status { get; set; }
        public Nullable<System.DateTime> Completed_Date { get; set; }
        public Nullable<double> C__Complete { get; set; }
        public Nullable<System.DateTime> Milestone_Due_Date { get; set; }
        public Nullable<System.DateTime> Milestone_Start_Date { get; set; }
        public Nullable<double> Task_Overdue { get; set; }
        public Nullable<double> Task__Record_ID { get; set; }
        public string Milestone__Region { get; set; }
        public Nullable<double> Milestone__Record_ID { get; set; }
        public string Milestone__Record_ID_Key { get; set; }
        public string Milestone__Project_Notes { get; set; }
        public string Milestone__Reason_Code { get; set; }
        public string Group_Name { get; set; }
        public string Milestone__Closed_Loop_Owner { get; set; }
        public string Milestone__Assignee__Full_Name { get; set; }
        public string Milestone__Override_Regional_Digital_OBT_Lead__Full_Name { get; set; }
        public string Milestone__Override_Regional_Digital_Portrait_Lead__Full_Name { get; set; }
        public string Milestone__Local_Digital_OBT_Lead { get; set; }
        public string Milestone__Local_Digital_Ad_Hoc_Support { get; set; }
    }
}
