//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long AuditID { get; set; }
        public double RevenueID { get; set; }
        public string UsedPlatForm { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Field { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string TaskRecordIDKey { get; set; }
        public string Status { get; set; }
        public Nullable<long> AuditEntryId { get; set; }
    }
}
