//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateLeadsOne
    {
        public int CLOID { get; set; }
        public Nullable<double> ID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Follow_Up { get; set; }
        public string Recruiter { get; set; }
        public string Priority { get; set; }
        public string Candidate_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Location { get; set; }
        public string Position { get; set; }
        public string Notes { get; set; }
        public string Zip_code { get; set; }
        public string Quality { get; set; }
        public string State_1_ { get; set; }
        public string State { get; set; }
        public string Open_Jobs { get; set; }
        public string Zipcode { get; set; }
    }
}
