//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityHierarchy
    {
        public int HID { get; set; }
        public string Region { get; set; }
        public string Level { get; set; }
        public string Leader { get; set; }
        public string WorkShedule { get; set; }
        public double Monday { get; set; }
        public double Tuesday { get; set; }
        public double Wednesday { get; set; }
        public double Thursday { get; set; }
        public double Friday { get; set; }
        public string Manager { get; set; }
        public string ProjectLevel { get; set; }
        public Nullable<double> WorkingDays { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public string PLevel { get; set; }
        public double TargetedUtilization { get; set; }
        public string ManagerStatus { get; set; }
        public string Comments { get; set; }
    }
}
