//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLR
    {
        public int CLRID { get; set; }
        public string Client { get; set; }
        public string iMeet_Workspace_Title { get; set; }
        public Nullable<System.DateTime> Date_added_to_the_CLR { get; set; }
        public string Implementation_Type { get; set; }
        public string CLR_Country { get; set; }
        public string Pipeline_status { get; set; }
        public string Pipeline_comments { get; set; }
        public string Service_configuration { get; set; }
        public string OBT_Reseller___Direct { get; set; }
        public string Servicing_location { get; set; }
        public Nullable<System.DateTime> Assignment_date { get; set; }
        public Nullable<double> New_Business_volume__US__ { get; set; }
        public Nullable<double> Revenue_Total_Volume_USD { get; set; }
        public string Region__Opportunity_ { get; set; }
        public string Country { get; set; }
        public Nullable<double> Revenue_ID { get; set; }
        public string Ownership__Revenue_ { get; set; }
        public Nullable<System.DateTime> Task__Go_Live_Date { get; set; }
        public string iMeet_Milestone___Project_Status { get; set; }
        public string iMeet_Milestone__Country_Status { get; set; }
        public string iMeet_Project_Level { get; set; }
        public Nullable<System.DateTime> iMeet_Milestone__Project_Start_Date { get; set; }
        public Nullable<System.DateTime> iMeet_Milestone___Initial_Go_Live_Date { get; set; }
        public string Milestone__Last_Go_Live_Date { get; set; }
        public Nullable<System.DateTime> Completed_Date { get; set; }
        public string Workspace__Project_Owner { get; set; }
        public string Global_Project_Manager { get; set; }
        public string Project_Consultant { get; set; }
        public string Regional_Project_Manager { get; set; }
        public string Milestone__Assignee__Full_Name { get; set; }
        public string Global_CIS_OBT_Lead { get; set; }
        public string Global_CIS_HR_Feed_Specialist { get; set; }
        public string Global_CIS_Portrait_Lead { get; set; }
        public string Global_CIS_RoomIT_Integration_Lead { get; set; }
        public string Milestone_Title { get; set; }
        public string Record_ID_Key { get; set; }
        public string Task__Go_Live_Date_Record_ID_Key { get; set; }
        public string Workspace_Group_Name { get; set; }
        public string Milestone__Project_Notes___Proposed_Risk_Mitigation_Solution___P { get; set; }
        public string Milestone__Reason_Code__H_On_Hold__X_Cancelled_ { get; set; }
        public string Milestone__Closed_Loop_Owner__H_On_Hold__X_Cancelled_ { get; set; }
        public string Workspace__ELT_Overall_Status { get; set; }
        public string Workspace__ELT_Overall_Comments { get; set; }
        public Nullable<double> Customer_Row_ID { get; set; }
        public Nullable<double> Opportunity_ID { get; set; }
        public string Account { get; set; }
        public string Sales_Stage_Name { get; set; }
        public string Opportunity_Type { get; set; }
        public string Revenue_Status { get; set; }
        public string Revenue_Opportunity_Type { get; set; }
        public string Opportunity_Owner { get; set; }
        public string Opportunity_Category { get; set; }
        public string Market_Leader { get; set; }
        public Nullable<double> Revenue___Total_Transactions { get; set; }
        public string EMEA_Country_to_charge { get; set; }
        public string EMEA_Client { get; set; }
        public string EMEA_OBT_standard_fee { get; set; }
        public string EMEA_Included_for_accrual { get; set; }
        public Nullable<System.DateTime> EMEA_Accrual_date { get; set; }
        public string EMEA_Scope_description { get; set; }
        public string EMEA_Billing_notes { get; set; }
        public string Survey_recipient_Name_1__Local_client_contact_ { get; set; }
        public string Survey_recipient_Email_1__Local_client_contact_ { get; set; }
        public Nullable<System.DateTime> Send_ { get; set; }
        public string Survey_recipient_Name_2__global__regional_client_contact_ { get; set; }
        public string Survey_recipient_Email_2__Global___Regional_client_contact_ { get; set; }
        public Nullable<System.DateTime> Send_1 { get; set; }
        public string Go_Live_Month_Year { get; set; }
        public string Go_Live_Month { get; set; }
        public string Go_Live_Year { get; set; }
        public string Backlog_Started { get; set; }
        public string Quarter { get; set; }
        public Nullable<System.DateTime> Milestone_Due_Date { get; set; }
        public string Global_PL_Leader { get; set; }
        public string Regional_PL_Leader { get; set; }
        public string Local_PL_Leader { get; set; }
        public string Project_Year { get; set; }
        public string Completed_Year { get; set; }
        public string Project_Sum { get; set; }
        public Nullable<double> C07_Jan { get; set; }
        public Nullable<double> C14_Jan { get; set; }
        public Nullable<double> C21_Jan { get; set; }
        public Nullable<double> C28_Jan { get; set; }
        public Nullable<double> C04_Feb { get; set; }
        public Nullable<double> C11_Feb { get; set; }
        public Nullable<double> C18_Feb { get; set; }
        public Nullable<double> C25_Feb { get; set; }
        public Nullable<double> C04_Mar { get; set; }
        public Nullable<double> C11_Mar { get; set; }
        public Nullable<double> C18_Mar { get; set; }
        public Nullable<double> C25_Mar { get; set; }
        public Nullable<double> C01_Apr { get; set; }
        public Nullable<double> C08_Apr { get; set; }
        public Nullable<double> C15_Apr { get; set; }
        public Nullable<double> C22_Apr { get; set; }
        public Nullable<double> C29_Apr { get; set; }
        public Nullable<double> C06_May { get; set; }
        public Nullable<double> C13_May { get; set; }
        public Nullable<double> C20_May { get; set; }
        public Nullable<double> C27_May { get; set; }
        public Nullable<double> C03_Jun { get; set; }
        public Nullable<double> C10_Jun { get; set; }
        public Nullable<double> C17_Jun { get; set; }
        public Nullable<double> C24_Jun { get; set; }
        public Nullable<double> C01_Jul { get; set; }
        public Nullable<double> C08_Jul { get; set; }
        public Nullable<double> C15_Jul { get; set; }
        public Nullable<double> C22_Jul { get; set; }
        public Nullable<double> C29_Jul { get; set; }
        public Nullable<double> C05_Aug { get; set; }
        public Nullable<double> C12_Aug { get; set; }
        public Nullable<double> C19_Aug { get; set; }
        public Nullable<double> C26_Aug { get; set; }
        public Nullable<double> C02_Sep { get; set; }
        public Nullable<double> C09_Sep { get; set; }
        public Nullable<double> C16_Sep { get; set; }
        public Nullable<double> C23_Sep { get; set; }
        public Nullable<double> C30_Sep { get; set; }
        public Nullable<double> C07_Oct { get; set; }
        public Nullable<double> C14_Oct { get; set; }
        public Nullable<double> C21_Oct { get; set; }
        public Nullable<double> C28_Oct { get; set; }
        public Nullable<double> C04_Nov { get; set; }
        public Nullable<double> C11_Nov { get; set; }
        public Nullable<double> C18_Nov { get; set; }
        public Nullable<double> C25_Nov { get; set; }
        public Nullable<double> C02_Dec { get; set; }
        public Nullable<double> C09_Dec { get; set; }
        public Nullable<double> C16_Dec { get; set; }
        public Nullable<double> C23_Dec { get; set; }
        public Nullable<double> C30_Dec { get; set; }
        public Nullable<double> Cycle_Time { get; set; }
    }
}
