//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLRActivity
    {
        public int A_ID { get; set; }
        public string Client { get; set; }
        public double Revenue_ID { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string ColumnName { get; set; }
        public string TaskRecordIDKey { get; set; }
    }
}
