//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLRBelowData
    {
        public int CLRID { get; set; }
        public Nullable<double> RevenueID { get; set; }
        public Nullable<double> RevenueVolumeUSD { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string OwnerShip { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string ProjectStatus { get; set; }
        public string Milestone__Reason_Code { get; set; }
        public Nullable<double> PerCompleted { get; set; }
        public string CountryStatus { get; set; }
        public string ProjectLevel { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> MilestoneDueDate { get; set; }
        public string ProjectOwner { get; set; }
        public string GlobalProjectManager { get; set; }
        public string ProjectConsultant { get; set; }
        public string RegionalProjectManager { get; set; }
        public string AssigneeFullName { get; set; }
        public string GlobalCISOBTLead { get; set; }
        public string RegionalCISOBTLead { get; set; }
        public string GlobalCISHRFeedSpecialist { get; set; }
        public string GlobalCISPortraitLead { get; set; }
        public string RegionalCISPortraitLead { get; set; }
        public string GlobalCISRoomITIntegrationLead { get; set; }
        public string MilestoneTitle { get; set; }
        public string Milestone__Record_ID_Key { get; set; }
        public string Task__Task_Record_ID_Key { get; set; }
        public string Group_Name { get; set; }
        public string Milestone__Project_Notes { get; set; }
        public string Milestone__Closed_Loop_Owner { get; set; }
        public string Workspace_Title { get; set; }
        public string Workspace__ELT_Overall_Status { get; set; }
        public string Workspace__ELT_Overall_Comments { get; set; }
        public Nullable<double> Customer_Row_ID { get; set; }
        public Nullable<double> Opportunity_ID { get; set; }
        public string Account_Name { get; set; }
        public string Sales_Stage_Name { get; set; }
        public string Opportunity_Type { get; set; }
        public string Revenue_Status { get; set; }
        public string Revenue_Opportunity_Type { get; set; }
        public string Opportunity_Owner { get; set; }
        public string Opportunity_Category { get; set; }
        public string MarketLeader { get; set; }
        public Nullable<double> Revenue_Total_Transactions { get; set; }
        public Nullable<double> Line_Win_Probability { get; set; }
        public string Next_Step { get; set; }
        public Nullable<double> Implementation_Fee_PSD { get; set; }
        public string CountryCode { get; set; }
        public string GoLiveMonth { get; set; }
        public string GoLiveYear { get; set; }
        public string BacklogStarted { get; set; }
        public string Quarter { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public Nullable<System.DateTime> ExternalKickoffDuedate { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> ProjectStartForCycleTime { get; set; }
    }
}
