//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLRColumnsHiding
    {
        public int CLRColumnId { get; set; }
        public bool Implementation_Type { get; set; }
        public bool Pipeline_status { get; set; }
        public bool Pipeline_comments { get; set; }
        public bool TXResourcing { get; set; }
        public bool Service_location { get; set; }
        public bool Service_configuration { get; set; }
        public bool OBT_Reseller___Direct { get; set; }
        public bool OBTAdoptionRate { get; set; }
        public bool ExpectedDecisionDate_c { get; set; }
        public bool Assignment_date_c { get; set; }
        public bool ResourseRequestedDate_c { get; set; }
        public bool UpdateOn_c { get; set; }
        public bool OppVolume { get; set; }
        public bool RevenueVolumeUSD { get; set; }
        public bool Region { get; set; }
        public bool OwnerShip { get; set; }
        public bool ProjectStart_ForCycleTime_c { get; set; }
        public bool GoLiveDate_c { get; set; }
        public bool PerCompleted { get; set; }
        public bool CycleTime { get; set; }
        public bool CycleTimeCategories { get; set; }
        public bool CycleTimeDelayCode { get; set; }
        public bool EltClientDelayDescription { get; set; }
        public bool ProjectStatus { get; set; }
        public bool Milestone__Reason_Code { get; set; }
        public bool CountryStatus { get; set; }
        public bool ProjectLevel { get; set; }
        public bool CompletedDate_c { get; set; }
        public bool GlobalProjectManager { get; set; }
        public bool RegionalProjectManager { get; set; }
        public bool AssigneeFullName { get; set; }
        public bool GlobalCISDQSLead { get; set; }
        public bool APAC_DQS { get; set; }
        public bool DQS_Import { get; set; }
        public bool DQS_Support { get; set; }
        public bool LATAM_DQS { get; set; }
        public bool NORAM_DQS { get; set; }
        public bool DQS_Operations { get; set; }
        public bool GlobalCISOBTLead { get; set; }
        public bool RegionalCISOBTLead { get; set; }
        public bool LocalDigitalOBTLead { get; set; }
        public bool GlobalCISPortraitLead { get; set; }
        public bool RegionalCISPortraitLead { get; set; }
        public bool GlobalCISHRFeedSpecialist { get; set; }
        public bool GDS { get; set; }
        public bool ActivityType { get; set; }
        public bool ComplexityScore { get; set; }
        public bool MilestoneTitle { get; set; }
        public bool Group_Name { get; set; }
        public bool Milestone__Project_Notes { get; set; }
        public bool Milestone__Closed_Loop_Owner { get; set; }
        public bool Workspace__ELT_Overall_Status { get; set; }
        public bool Workspace__ELT_Overall_Comments { get; set; }
        public bool NpsScore { get; set; }
        public bool Customer_Row_ID { get; set; }
        public bool Opportunity_ID { get; set; }
        public bool AccountOwner { get; set; }
        public bool Opportunity_Type { get; set; }
        public bool Revenue_Status { get; set; }
        public bool Revenue_Opportunity_Type { get; set; }
        public bool Opportunity_Owner { get; set; }
        public bool Opportunity_Category { get; set; }
        public bool Revenue_Total_Transactions { get; set; }
        public bool Line_Win_Probability { get; set; }
        public bool Implementation_Fee__PSD_ { get; set; }
        public bool Next_Step { get; set; }
        public bool AwardedDate_c { get; set; }
        public bool DataDescription { get; set; }
        public bool Date_added_to_the_CLR_c { get; set; }
        public bool CreatedDate_c { get; set; }
        public bool Project_Effort { get; set; }
        public bool Sales_Stage_Name { get; set; }
        public bool AccountCategory { get; set; }
        public bool SOWStatus { get; set; }
        public bool ImplementationReady { get; set; }
        public bool RecordHistory_C { get; set; }
        public bool DataSourceType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UID { get; set; }
        public Nullable<bool> Priority { get; set; }
        public Nullable<bool> DataQuality { get; set; }
    }
}
