//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLRData
    {
        public int CLRID { get; set; }
        public double RevenueID { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string OwnerShip { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string ProjectStatus { get; set; }
        public string CountryStatus { get; set; }
        public string ProjectLevel { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string ProjectOwner { get; set; }
        public string AssigneeFullName { get; set; }
        public string MilestoneTitle { get; set; }
        public string Milestone__Record_ID_Key { get; set; }
        public string Task__Task_Record_ID_Key { get; set; }
        public string Group_Name { get; set; }
        public string Milestone__Project_Notes { get; set; }
        public string Milestone__Reason_Code { get; set; }
        public string Milestone__Closed_Loop_Owner { get; set; }
        public string Workspace_Title { get; set; }
        public string Workspace__ELT_Overall_Status { get; set; }
        public string Workspace__ELT_Overall_Comments { get; set; }
        public Nullable<double> Customer_Row_ID { get; set; }
        public Nullable<double> Opportunity_ID { get; set; }
        public string Account_Name { get; set; }
        public string Sales_Stage_Name { get; set; }
        public string Opportunity_Type { get; set; }
        public string Revenue_Opportunity_Type { get; set; }
        public string Revenue_Status { get; set; }
        public string Opportunity_Owner { get; set; }
        public string Opportunity_Category { get; set; }
        public Nullable<double> Revenue_Total_Transactions { get; set; }
        public string CountryCode { get; set; }
        public Nullable<double> RevenueVolumeUSD { get; set; }
        public string MarketLeader { get; set; }
        public string GlobalProjectManager { get; set; }
        public string ProjectConsultant { get; set; }
        public string RegionalProjectManager { get; set; }
        public string GlobalCISOBTLead { get; set; }
        public string GlobalCISHRFeedSpecialist { get; set; }
        public string GlobalCISPortraitLead { get; set; }
        public string GoLiveMonth { get; set; }
        public string GoLiveYear { get; set; }
        public string BacklogStarted { get; set; }
        public string Quarter { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public Nullable<System.DateTime> ExternalKickoffDuedate { get; set; }
        public Nullable<int> PerCompleted { get; set; }
        public Nullable<System.DateTime> MilestoneDueDate { get; set; }
        public string Next_Step { get; set; }
        public Nullable<int> Line_Win_Probability { get; set; }
        public string Client { get; set; }
        public string RegionalCISOBTLead { get; set; }
        public string RegionalCISPortraitLead { get; set; }
        public Nullable<System.DateTime> ProjectStart_ForCycleTime { get; set; }
        public string Status { get; set; }
        public string ImplementationType { get; set; }
        public string DataSourceType { get; set; }
        public string DataDescription { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> AwardedDate { get; set; }
        public string MilestoneType { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<double> ImplementationFeePsd { get; set; }
        public string AccountOwner { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CycleTimeCategories { get; set; }
        public string LocalDigitalOBTLead { get; set; }
        public string GDS { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<double> ComplexityScore { get; set; }
        public string YearMonth { get; set; }
        public string OBTReseller { get; set; }
        public string DigitalGDS { get; set; }
        public string DigitalActivityType { get; set; }
        public string SOWStatus { get; set; }
        public string ImplementationReady { get; set; }
        public string AccountCategory { get; set; }
        public Nullable<double> OppTOtalVolume { get; set; }
        public string eSowGDS { get; set; }
        public string Service_Configuration { get; set; }
        public string LocalDigitalAdHocSupport { get; set; }
        public string Project_Level { get; set; }
        public string GlobalCISDQSLead { get; set; }
        public string Service_Location { get; set; }
        public string OBTAdoptionRate { get; set; }
        public string CycleTimeDelayCode { get; set; }
        public string APAC_DQS { get; set; }
        public string DQS_Import { get; set; }
        public string DQS_Support { get; set; }
        public string LATAM_DQS { get; set; }
        public string NORAM_DQS { get; set; }
        public string DQS_Operations { get; set; }
        public string EltClientDelayDescription { get; set; }
        public string Priority { get; set; }
    }
}
