//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLRResourceUtilization
    {
        public int RUid { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public string Region { get; set; }
        public string Level { get; set; }
        public string ProjectLevel { get; set; }
        public string Leader { get; set; }
        public string Manager { get; set; }
        public string WorkShedule { get; set; }
        public Nullable<double> WorkingDays { get; set; }
        public Nullable<double> Monday { get; set; }
        public Nullable<double> Tuesday { get; set; }
        public Nullable<double> Wednesday { get; set; }
        public Nullable<double> Thursday { get; set; }
        public Nullable<double> Friday { get; set; }
        public string Comments { get; set; }
        public Nullable<double> TargetedUtilization { get; set; }
        public Nullable<double> C1stweek { get; set; }
        public Nullable<double> C2ndweek { get; set; }
        public Nullable<double> C3rdweek { get; set; }
        public Nullable<double> C4thweek { get; set; }
        public Nullable<double> C5thweek { get; set; }
        public Nullable<double> C6thweek { get; set; }
        public Nullable<double> C7thweek { get; set; }
        public Nullable<double> C8thweek { get; set; }
        public Nullable<double> AvgUtil { get; set; }
        public Nullable<double> TUWorkingDays { get; set; }
        public Nullable<double> CapacityAvailable { get; set; }
        public Nullable<double> CapacityAvailableTUWorkingDays { get; set; }
        public Nullable<double> C9thweek { get; set; }
        public Nullable<double> C10thweek { get; set; }
        public Nullable<double> C11thweek { get; set; }
        public Nullable<double> C12thweek { get; set; }
        public Nullable<double> c13thweek { get; set; }
        public Nullable<double> c14thweek { get; set; }
        public Nullable<double> c15thweek { get; set; }
        public Nullable<double> c16thweek { get; set; }
        public Nullable<double> c17thweek { get; set; }
        public Nullable<double> c18thweek { get; set; }
        public Nullable<double> c19thweek { get; set; }
        public Nullable<double> c20thweek { get; set; }
        public Nullable<double> c21thweek { get; set; }
        public Nullable<double> c22thweek { get; set; }
        public Nullable<double> c23thweek { get; set; }
        public Nullable<double> c24thweek { get; set; }
        public string ProjectStatus { get; set; }
    }
}
