//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLRTracker
    {
        public int TrackerId { get; set; }
        public double RevenueID { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string GlobalProjectManager { get; set; }
        public string RegionalProjectManager { get; set; }
        public string LocalProjectManager { get; set; }
        public string Client { get; set; }
        public string iMeetWorkspaceTitle { get; set; }
        public string OwnershipType { get; set; }
        public string PriorityCustomer { get; set; }
        public Nullable<double> Volume { get; set; }
        public string ProjectLevel { get; set; }
        public string ImplementationType { get; set; }
        public string ProjectStatus { get; set; }
        public string GlobalDigitalOBTLead { get; set; }
        public string RegionalDigitalOBTLead { get; set; }
        public string GlobalDigitalPortraitLead { get; set; }
        public string RegionalDigitalPortraitLead { get; set; }
        public string GlobalDigitalHRFeedSpeciallist { get; set; }
        public string MilestoneProjectNotes { get; set; }
        public Nullable<double> ProjectEffort { get; set; }
        public Nullable<System.DateTime> KickOff_ProposedStartDate { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public Nullable<System.DateTime> EndofHypercare { get; set; }
        public string CompleteDuration { get; set; }
        public Nullable<double> PerCompleted { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> MilestoneDueDate { get; set; }
        public Nullable<double> ProjectDelay { get; set; }
        public Nullable<double> C1stweek { get; set; }
        public Nullable<double> C2ndweek { get; set; }
        public Nullable<double> C3rdweek { get; set; }
        public Nullable<double> C4thweek { get; set; }
        public Nullable<double> C5thweek { get; set; }
        public Nullable<double> C6thweek { get; set; }
        public Nullable<double> C7thweek { get; set; }
        public Nullable<double> C8thweek { get; set; }
        public Nullable<double> C9thweek { get; set; }
        public Nullable<double> C10thweek { get; set; }
        public Nullable<double> C11thweek { get; set; }
        public Nullable<double> C12thweek { get; set; }
        public Nullable<double> c13thweek { get; set; }
        public Nullable<double> c14thweek { get; set; }
        public Nullable<double> c15thweek { get; set; }
        public Nullable<double> c16thweek { get; set; }
        public Nullable<double> c17thweek { get; set; }
        public Nullable<double> c18thweek { get; set; }
        public Nullable<double> c19thweek { get; set; }
        public Nullable<double> c20thweek { get; set; }
        public Nullable<double> c21thweek { get; set; }
        public Nullable<double> c22thweek { get; set; }
        public Nullable<double> c23thweek { get; set; }
        public Nullable<double> c24thweek { get; set; }
        public Nullable<int> Jan { get; set; }
        public Nullable<int> Feb { get; set; }
        public Nullable<int> Mar { get; set; }
        public Nullable<int> Apr { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> Jun { get; set; }
        public Nullable<int> Jul { get; set; }
        public Nullable<int> Aug { get; set; }
        public Nullable<int> Sep { get; set; }
        public Nullable<int> Oct { get; set; }
        public Nullable<int> Nov { get; set; }
        public Nullable<int> Dec { get; set; }
        public string LocalDigitalOBTLead { get; set; }
        public string GDS { get; set; }
        public Nullable<double> ComplexityScore { get; set; }
        public string TaskRecordIdKey { get; set; }
    }
}
