//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConfigID { get; set; }
        public string ProjectType { get; set; }
        public double Duration { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
