//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTO
    {
        public int CTOID { get; set; }
        public string Milestone_Title_Country___Est_Go_Live_Date { get; set; }
        public Nullable<double> Critical_Overdue { get; set; }
        public Nullable<System.DateTime> Estimated_Go_Live { get; set; }
        public string Workspace_Title { get; set; }
        public string Milestone__Project_Status { get; set; }
        public string Group_Name { get; set; }
        public string Milestone__Region { get; set; }
        public string Milestone_Title { get; set; }
        public string Milestone__Assignee__Full_Name { get; set; }
        public Nullable<System.DateTime> Milestone_Due_Date { get; set; }
        public string Milestone__Country_Status { get; set; }
        public string Task_List_Title { get; set; }
        public string Task_Title { get; set; }
        public string Task__Assignee__Full_Name { get; set; }
        public string Task_Status { get; set; }
        public Nullable<double> Task_Overdue { get; set; }
        public Nullable<System.DateTime> Task_Start_Date { get; set; }
        public Nullable<System.DateTime> Task_Due_Date { get; set; }
        public string Workspace__Project_Level { get; set; }
        public Nullable<System.DateTime> Milestone__Project_Start_Date { get; set; }
        public string Milestone__Country { get; set; }
        public string Last_Comment { get; set; }
        public Nullable<double> RevenurID { get; set; }
    }
}
