//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CWTEntities : DbContext
    {
        public CWTEntities()
            : base("name=CWTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CountryIsoCode> CountryIsoCodes { get; set; }

        public virtual DbSet<CTO> CTOes { get; set; }
        public virtual DbSet<IMP> IMPS { get; set; }
        public virtual DbSet<eSOWNew> eSOWs { get; set; }
        public virtual DbSet<StageGate> StageGates { get; set; }
    }
}
