//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELTDeltaComment
    {
        public int EltCommentsId { get; set; }
        public string Client { get; set; }
        public string WorkspaceTitle { get; set; }
        public string Month { get; set; }
        public double Year { get; set; }
        public double Revenue { get; set; }
        public double RevenueId { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string Comment { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string Status { get; set; }
        public string DeltaColor { get; set; }
    }
}
