//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EltOldCLRData
    {
        public int CLRID { get; set; }
        public string Client { get; set; }
        public double RevenueID { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string OwnerShip { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectLevel { get; set; }
        public string Workspace_Title { get; set; }
        public string Workspace__ELT_Overall_Status { get; set; }
        public string Workspace__ELT_Overall_Comments { get; set; }
        public string Opportunity_Type { get; set; }
        public Nullable<double> RevenueVolumeUSD { get; set; }
        public string GoLiveMonth { get; set; }
        public string GoLiveYear { get; set; }
        public string Quarter { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public Nullable<System.DateTime> ProjectStart_ForCycleTime { get; set; }
        public string Status { get; set; }
        public string ImplementationType { get; set; }
        public string DataSourceType { get; set; }
        public string TaskRecordIdKey { get; set; }
    }
}
