//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorTracker
    {
        public int TrackerID { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string ResourceName { get; set; }
        public string Manager { get; set; }
        public string ProjectLevel { get; set; }
        public string OBT { get; set; }
        public string OBTUsed { get; set; }
        public string TypeofError { get; set; }
        public string FinancialImpact { get; set; }
        public string FIDescription { get; set; }
        public double ValueofLoss { get; set; }
        public string ErrorDescription { get; set; }
        public string ErrorReason { get; set; }
        public string WhoReportedError { get; set; }
        public string ErrorComplexityRating { get; set; }
        public string IssueResolved { get; set; }
        public string Comments { get; set; }
        public string FMEA { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string Status { get; set; }
    }
}
