//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eSowData
    {
        public int eSowID { get; set; }
        public string SOWName { get; set; }
        public string ServiceModel { get; set; }
        public string LanguageRequirement { get; set; }
        public string DSDLead { get; set; }
        public string SOWOwner { get; set; }
        public string ImplementationLead { get; set; }
        public string PricingLead { get; set; }
        public string PricingLeadregion { get; set; }
        public string GeographicScope { get; set; }
        public string ProspectType { get; set; }
        public string CRMStatus { get; set; }
        public string ClientRegion { get; set; }
        public Nullable<System.DateTime> DateRFPReceived { get; set; }
        public Nullable<System.DateTime> SOWCreationDate { get; set; }
        public Nullable<System.DateTime> DateDecisionExpected { get; set; }
        public Nullable<System.DateTime> Datenotifiedofwinorloss { get; set; }
        public Nullable<System.DateTime> GoLivedateestimated { get; set; }
        public Nullable<double> NumberofCountries { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string WebPEMStatus { get; set; }
        public string SOWStatus { get; set; }
        public string SLAInScope { get; set; }
        public string PricingReady { get; set; }
        public string ImplementationReady { get; set; }
        public string AccountCategory { get; set; }
        public string PenaltyRewardSLA { get; set; }
        public string SLAReporting { get; set; }
        public Nullable<double> CRMOpportunityID { get; set; }
    }
}
