//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class esowNewData
    {
        public int ESOWid { get; set; }
        public string Client { get; set; }
        public Nullable<double> id { get; set; }
        public string eSoW_Ref { get; set; }
        public Nullable<double> crmOpportunityId { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string Client_Type { get; set; }
        public string Proposal_Type { get; set; }
        public string Account_Owner { get; set; }
        public string SoW_Owner { get; set; }
        public string Self_Service { get; set; }
        public string eSoW_Status { get; set; }
        public string CRM_Status { get; set; }
        public string Option { get; set; }
        public string Country_Name { get; set; }
        public Nullable<double> serviceConfig { get; set; }
        public string Team { get; set; }
        public string configLoc { get; set; }
        public string configName { get; set; }
        public string afterHours { get; set; }
        public string GDS { get; set; }
        public string OBT { get; set; }
        public string Account_Category { get; set; }
        public string implementationReady { get; set; }
        public string Direct_Reseller { get; set; }
        public Nullable<double> OBT_Adoption_Rate { get; set; }
    }
}
