//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hierarchy
    {
        public int HierarchyID { get; set; }
        public string User_ID { get; set; }
        public string Name { get; set; }
        public string Sr_Leader { get; set; }
        public string VP { get; set; }
        public string Email_Address { get; set; }
        public string Region { get; set; }
        public string Location { get; set; }
        public string Role { get; set; }
        public string Title { get; set; }
        public string UserStatus { get; set; }
        public string LeaderOne { get; set; }
        public string LeaderTwo { get; set; }
    }
}
