//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP
    {
        public int IMPSID { get; set; }
        public string Workspace_Title { get; set; }
        public Nullable<double> Workspace__CRM_Customer_Row_ID { get; set; }
        public string Workspace__Project_Level { get; set; }
        public string Workspace__ELT_Overall_Status { get; set; }
        public string Workspace__ELT_Overall_Comments { get; set; }
        public string Milestone_Title { get; set; }
        public string Milestone__Region { get; set; }
        public string Milestone__Record_ID_Key { get; set; }
        public string Milestone__Country { get; set; }
        public string Milestone__Project_Status { get; set; }
        public Nullable<double> C__Complete { get; set; }
        public Nullable<double> Milestone__Project_Start_Date { get; set; }
        public string Milestone__Assignee__Full_Name { get; set; }
        public string Milestone__Assignee__Reports_to__Full_Name { get; set; }
        public string Task_Title { get; set; }
        public string Task__Task_Record_ID_Key { get; set; }
        public Nullable<double> Task_Start_Date { get; set; }
        public Nullable<double> Milestone__CRM_Revenue_ID__ { get; set; }
        public string Milestone__Project_Notes { get; set; }
        public string Milestone__Reason_Code { get; set; }
        public string Milestone__Closed_Loop_Owner { get; set; }
    }
}
