//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiraData
    {
        public int JiraId { get; set; }
        public string Summary { get; set; }
        public string Assignee { get; set; }
        public string Assignee_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Custom_field__Flight_Planned_Go_Live_Date_ { get; set; }
        public Nullable<System.DateTime> Custom_field__Flight_Project_Complete_Date_ { get; set; }
        public Nullable<System.DateTime> Custom_field__Flight_Project_Start_Date_ { get; set; }
        public string Custom_field__Flight_Trx_Monthly_ { get; set; }
        public string Custom_field__GDS_ { get; set; }
        public string Custom_field__GUID_Client_Top_ { get; set; }
        public Nullable<System.DateTime> Custom_field__Hotel_Planned_Go_Live_Date_ { get; set; }
        public Nullable<System.DateTime> Custom_field__Hotel_Project_Complete_Date_ { get; set; }
        public Nullable<System.DateTime> Custom_field__Hotel_Project_Start_Date_ { get; set; }
        public string Custom_field__Hotel_Trx_Monthly_ { get; set; }
        public string Custom_field__Implementation_Type_ { get; set; }
        public string Issue_Type { get; set; }
        public Nullable<System.DateTime> Last_Viewed { get; set; }
        public string Custom_field__Market__DIGI__ { get; set; }
        public string Custom_field__OBT_Contract_ { get; set; }
        public string Custom_field__OBT_Used_ { get; set; }
        public string Priority { get; set; }
        public string Custom_field__Project_Contact_ { get; set; }
        public string Status { get; set; }
        public string Status_Category { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
