//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeBase
    {
        public int KBId { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string Comments { get; set; }
        public string Keywords { get; set; }
        public string Source { get; set; }
        public string Type { get; set; }
    }
}
