//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonLearnt
    {
        public int LLID { get; set; }
        public string iMeet_Workspace_Title { get; set; }
        public string Record_ID { get; set; }
        public Nullable<System.DateTime> Date_feedback_raised { get; set; }
        public string Country_Area_of_Responsibility { get; set; }
        public string Region { get; set; }
        public string What_was_the_event_issue_concern { get; set; }
        public string Is_there_any_specific_recognition_to_a_person_group_process_rela { get; set; }
        public Nullable<System.DateTime> Go_Live_Date { get; set; }
        public string Reason_Type { get; set; }
        public string Created_by_Field { get; set; }
        public string Leader { get; set; }
        public string Reason_Code__Added_by_Leader_ { get; set; }
        public string What_do_you_recommend___to_avoid_this_occurring_again_in_future { get; set; }
        public string Status__By_Leader_ { get; set; }
        public string Action_Taken__By_Leader_ { get; set; }
    }
}
