//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonsLearnt
    {
        public int LessonsLearntID { get; set; }
        public string iMeet_Workspace_Title { get; set; }
        public string Record_ID { get; set; }
        public Nullable<System.DateTime> Date_feedback_raised { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string What_did_not_go_well { get; set; }
        public string What_went_well { get; set; }
        public string Raised_by { get; set; }
        public Nullable<System.DateTime> Go_Live_Date { get; set; }
        public string Owner { get; set; }
        public string Status { get; set; }
        public string Actions { get; set; }
    }
}
