//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualData
    {
        public int ManualID { get; set; }
        public Nullable<double> Revenue_ID { get; set; }
        public string Client { get; set; }
        public string iMeet_Workspace_Title { get; set; }
        public string Implementation_Type { get; set; }
        public string CLR_Country { get; set; }
        public string Pipeline_status { get; set; }
        public string Pipeline_comments { get; set; }
        public string Service_configuration { get; set; }
        public string OBT_Reseller___Direct { get; set; }
        public string Servicing_location { get; set; }
        public Nullable<System.DateTime> Assignment_date { get; set; }
        public Nullable<double> Project_Effort { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string GlobalProjectManager { get; set; }
        public string RegionalProjectManager { get; set; }
        public string AssigneeFullName { get; set; }
        public string Status { get; set; }
        public string ProjectStatus { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
        public string TaskRecordIdKey { get; set; }
        public string ProjectLevel { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string Project_Level { get; set; }
        public string GlobalCISDQSLead { get; set; }
        public Nullable<System.DateTime> ResourseRequestedDate { get; set; }
    }
}
