//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthWiseDelta
    {
        public int DeltaID { get; set; }
        public double Jan { get; set; }
        public double Feb { get; set; }
        public double Mar { get; set; }
        public double Apr { get; set; }
        public double May { get; set; }
        public double Jun { get; set; }
        public double Jul { get; set; }
        public double Aug { get; set; }
        public double Sep { get; set; }
        public double Oct { get; set; }
        public double Nov { get; set; }
        public double Dec { get; set; }
        public string Year { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public string Jan_Comments { get; set; }
        public string Feb_Comments { get; set; }
        public string Mar_Comments { get; set; }
        public string Apr_Comments { get; set; }
        public string May_Comments { get; set; }
        public string Jun_Comments { get; set; }
        public string Jul_Comments { get; set; }
        public string Aug_Comments { get; set; }
        public string Sep_Comments { get; set; }
        public string Oct_Comments { get; set; }
        public string Nov_Comments { get; set; }
        public string Dec_Comments { get; set; }
        public double CV_Jan { get; set; }
        public double CV_Feb { get; set; }
        public double CV_Mar { get; set; }
        public double CV_Apr { get; set; }
        public double CV_May { get; set; }
        public double CV_Jun { get; set; }
        public double CV_Jul { get; set; }
        public double CV_Aug { get; set; }
        public double CV_Sep { get; set; }
        public double CV_Oct { get; set; }
        public double CV_Nov { get; set; }
        public double CV_Dec { get; set; }
    }
}
