//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NpsImp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NpsImp()
        {
            this.SurveySentDetails = new HashSet<SurveySentDetail>();
        }
    
        public int NpsId { get; set; }
        public string ClientName { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> DateServeySent { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string GlobalProjectManager { get; set; }
        public string RegionalProjectManager { get; set; }
        public string LocalProjectManager { get; set; }
        public string ClientScope { get; set; }
        public string ClientType { get; set; }
        public string CustomerContactNumber { get; set; }
        public string SingleResource { get; set; }
        public string DQS { get; set; }
        public string DSD { get; set; }
        public string OnlineTeam { get; set; }
        public Nullable<System.DateTime> DateSurveyReceived { get; set; }
        public string Status { get; set; }
        public string AssignLeaderForClosedLoop { get; set; }
        public Nullable<double> NPSScore { get; set; }
        public string NPSIndicator { get; set; }
        public string NPSCommentsWhatwasPositive { get; set; }
        public string NPSComments_Howcouldwehaveimproved { get; set; }
        public string NPSComments_Whatistheonethingwecandotomakeyouhappier { get; set; }
        public string ReasonType { get; set; }
        public string ClientFeedback { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string Language { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string NPSCommentsOne { get; set; }
        public string NPSCommentsTwo { get; set; }
        public string NPSCommentsThree { get; set; }
        public string RecordStatus { get; set; }
        public string YearMonth { get; set; }
        public Nullable<double> OpprtunityId { get; set; }
        public string GlobalDigitalPM { get; set; }
        public string RegionalDigitalPM { get; set; }
        public string LocalDigitalPM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveySentDetail> SurveySentDetails { get; set; }
    }
}
