//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineProjectTracker
    {
        public int OPTID { get; set; }
        public System.DateTime Golive { get; set; }
        public System.DateTime ActualGoLive { get; set; }
        public System.DateTime ProjectAssignedDate { get; set; }
        public System.DateTime KickOffImplementation { get; set; }
        public string ClientName { get; set; }
        public string ProjectType { get; set; }
        public string Business { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string OnlineBookingTool { get; set; }
        public string OnlineBookingType { get; set; }
        public string AssignedTo { get; set; }
        public string Manager { get; set; }
        public string ProjectStatus { get; set; }
        public string Comments { get; set; }
        public int NoOfCountries { get; set; }
    }
}
