//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerAutomate
    {
        public int PowerAutomateID { get; set; }
        public string AccountName { get; set; }
        public string Country { get; set; }
        public string ImplementationType { get; set; }
        public string ServiceLocation { get; set; }
        public string PipelineStatus { get; set; }
        public string ServiceConfiguration { get; set; }
        public string OBTType { get; set; }
        public double RevenueVolumeUSD { get; set; }
        public string Region { get; set; }
        public Nullable<double> OpportunityID { get; set; }
        public string NextStep { get; set; }
        public string Description { get; set; }
        public string OpportunityOwner { get; set; }
        public string OWNEREMAILIS { get; set; }
    }
}
