//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousMonthsElt
    {
        public int EltId { get; set; }
        public string Client { get; set; }
        public Nullable<double> EMEA { get; set; }
        public Nullable<double> APAC { get; set; }
        public Nullable<double> LATAM { get; set; }
        public Nullable<double> NORAM { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> NBAPriorMonth { get; set; }
        public Nullable<double> TotalAccountVolume { get; set; }
        public Nullable<double> Delta { get; set; }
        public string Comments { get; set; }
        public string Month { get; set; }
        public Nullable<double> Year { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
    }
}
