//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progression
    {
        public int ID { get; set; }
        public string Workspace_Title { get; set; }
        public string Task_List_Title { get; set; }
        public string Task_Title { get; set; }
        public string Milestone_Title { get; set; }
        public string Milestone__Created_by__Full_Name { get; set; }
        public Nullable<System.DateTime> Task_Start_Date { get; set; }
        public Nullable<System.DateTime> Task_Due_Date { get; set; }
        public Nullable<double> Budgeted_Time { get; set; }
        public string Task_Status { get; set; }
        public string Task__Action_Region { get; set; }
        public string Milestone__Project_Status { get; set; }
        public Nullable<double> Milestone__CRM_Revenue_ID__ { get; set; }
        public string Milestone__Assignee__Country { get; set; }
    }
}
