//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectType
    {
        public int ProjectTypeID { get; set; }
        public string ProjectType1 { get; set; }
        public double Duration { get; set; }
        public double PostGoLiveSupport { get; set; }
        public double ProjectEffortAPAC { get; set; }
        public double ProjectEffortEMEA { get; set; }
        public double ProjectEffortLATAM { get; set; }
        public double ProjectEffortNORAM { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
