//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospect
    {
        public int PID { get; set; }
        public string Region { get; set; }
        public string Manager { get; set; }
        public string Leader { get; set; }
        public string Client_Name { get; set; }
        public string InsertedBy { get; set; }
        public System.DateTime InsertedDate { get; set; }
    }
}
