//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSD
    {
        public int PSDID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Requestor { get; set; }
        public string Account_Name { get; set; }
        public string Account_Owner { get; set; }
        public Nullable<double> Customer_Row_ID { get; set; }
        public string Account_Category { get; set; }
        public string BT_Account_Record_Type { get; set; }
        public string Company_Alias { get; set; }
        public Nullable<double> Opportunity_ID { get; set; }
        public string Description { get; set; }
        public string Industry { get; set; }
        public string BT_Current_Service_Configuration { get; set; }
        public string BT_Current_GDS { get; set; }
        public string BT_Current_Online_Booking_Tool { get; set; }
        public string BT_Incumbent { get; set; }
        public string Opportunity_Name { get; set; }
        public string Product_Name { get; set; }
        public string Line_of_Business { get; set; }
        public string Opportunity_Owner { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public string Sales_Stage_Name { get; set; }
        public Nullable<double> Line_Win_Probability { get; set; }
        public string Initiative_Name { get; set; }
        public string Opportunity_Type { get; set; }
        public string Opportunity_Region { get; set; }
        public string Country_Scope { get; set; }
        public string Energy__Resources___Marine { get; set; }
        public string Invoicing_Period { get; set; }
        public string Pricing_Model { get; set; }
        public Nullable<double> PSD_Price_per_Transaction { get; set; }
        public Nullable<double> Total_Transactions { get; set; }
        public string Country { get; set; }
        public string Region__Revenue_ { get; set; }
        public string Implementation_Status { get; set; }
        public Nullable<double> Total_Revenue_USD { get; set; }
        public Nullable<System.DateTime> Estimated_Implementation_Start_Date { get; set; }
        public Nullable<System.DateTime> Implementation_End_Date { get; set; }
        public Nullable<double> Implementation_Fee { get; set; }
        public Nullable<System.DateTime> Go_Live_Date { get; set; }
        public Nullable<double> Revenue_Car_Volume_USD { get; set; }
        public string Revenue_Status { get; set; }
        public Nullable<double> Revenue_Id { get; set; }
        public Nullable<System.DateTime> Last_Update_Date { get; set; }
        public string Ownership__Revenue_ { get; set; }
    }
}
