//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RisksGap
    {
        public int RGID { get; set; }
        public Nullable<int> SCID { get; set; }
        public string RisksGaps { get; set; }
        public string MitigationPlan { get; set; }
        public string SteeringCommitteeSupportNeed { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Status { get; set; }
        public string Record_Status { get; set; }
        public string Risks { get; set; }
    
        public virtual SteeringCommittee SteeringCommittee { get; set; }
    }
}
