//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int RolesId { get; set; }
        public string Workspace_Title { get; set; }
        public string Global_Project_Manager { get; set; }
        public string Regional_Ops_Manager { get; set; }
        public string LATAM_Project_Manager { get; set; }
        public string NORAM_Project_Manager { get; set; }
        public string EMEA_Project_Manager { get; set; }
        public string Global_CIS_OBT_Lead { get; set; }
        public string LATAM_CIS_OBT_Lead { get; set; }
        public string NORAM_CIS_OBT_Lead { get; set; }
        public string EMEA_CIS_OBT_Lead { get; set; }
        public string Global_CIS_HR_Feed_Specialist { get; set; }
        public string Global_CIS_Portrait_Lead { get; set; }
        public string LATAM_CIS_Portrait_Lead { get; set; }
        public string EMEA_CIS_Portrait_Lead { get; set; }
        public string NORAM_CIS_Portrait_Lead { get; set; }
        public string Global_CIS_RoomIT_Integration_lead { get; set; }
        public string APAC_Implementation_Lead { get; set; }
        public string APAC_Digital_OBT_Lead { get; set; }
        public string APAC_Digital_Portrait_Lead { get; set; }
        public string Local_IN_CIS_Lead { get; set; }
        public string Global_CIS_DQS_Lead { get; set; }
        public string APAC_DQS { get; set; }
        public string DQS_Import { get; set; }
        public string DQS_Support { get; set; }
        public string LATAM_DQS { get; set; }
        public string NORAM_DQS { get; set; }
        public string DQS_Operations { get; set; }
    }
}
