//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageGate
    {
        public int StageGateID { get; set; }
        public string Task_Title { get; set; }
        public Nullable<System.DateTime> Task_Start_Date { get; set; }
        public Nullable<System.DateTime> Task_Due_Date { get; set; }
        public string Workspace_Title { get; set; }
        public string Task__Assignee__Full_Name { get; set; }
        public string Milestone__Assignee__Full_Name { get; set; }
        public string Milestone__Assignee__Reports_to__Full_Name { get; set; }
        public string Task_Status { get; set; }
        public string Milestone__Assignee__Country { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string ReportName { get; set; }
        public string Milestone__Project_Status { get; set; }
    }
}
