//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SteeringCommittee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SteeringCommittee()
        {
            this.RisksGaps = new HashSet<RisksGap>();
            this.Waves = new HashSet<Wave>();
        }
    
        public int SCID { get; set; }
        public string RecordStatus { get; set; }
        public string ClientName { get; set; }
        public string ClientType { get; set; }
        public string ProjectLead { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectTrend { get; set; }
        public double TotalBusineesVolume { get; set; }
        public double NewBusinessVolume { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string CurrentState { get; set; }
        public string CompletedKeyDeliverables { get; set; }
        public string ScheduledKeyDeliverables { get; set; }
        public string AdditionalNotes { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Record_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisksGap> RisksGaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wave> Waves { get; set; }
    }
}
