//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySentDetail
    {
        public int ID { get; set; }
        public int RecipientId { get; set; }
        public System.DateTime SurverySentOn { get; set; }
        public string SurveyLink { get; set; }
        public string CompanyName { get; set; }
        public string ClientName { get; set; }
        public string ClientEmailAddress { get; set; }
        public int NpsId { get; set; }
    
        public virtual NpsImp NpsImp { get; set; }
    }
}
