//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetCycleTime
    {
        public int TargetID { get; set; }
        public string ExistingServiceConfigChange { get; set; }
        public string NewGlobal { get; set; }
        public string NewRegional { get; set; }
        public string NewLocal { get; set; }
        public string Overall { get; set; }
        public string ExistingAddChange { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Year { get; set; }
        public string Months { get; set; }
    }
}
