//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracker
    {
        public int TrackerId { get; set; }
        public string Region__CRM_ { get; set; }
        public string Country_CRM_ { get; set; }
        public string Global_Project_Manager__iMeet_ { get; set; }
        public string Regional_Project_Manager__iMeet_ { get; set; }
        public string Local_Project_Manager__iMeet_ { get; set; }
        public string Client__Manual_Entry_ { get; set; }
        public string iMeet_Workspace_Title__iMeet_ { get; set; }
        public string Ownership_Type_CRM_ { get; set; }
        public string Priority_Customer__COVID_19_ { get; set; }
        public Nullable<double> Volume__CRM_ { get; set; }
        public string iMeet_Project_Level__iMeet_ { get; set; }
        public string Implementation_Type__CRM_ { get; set; }
        public string Current_Project_Status__iMeet_ { get; set; }
        public string CIS_Resource__iMeet_ { get; set; }
        public string Project_Details { get; set; }
        public Nullable<double> Project_Effort__Formula_ { get; set; }
        public Nullable<System.DateTime> Proposed_Start_Date__iMeet_ { get; set; }
        public Nullable<System.DateTime> Proposed_End_Date__Formula_ { get; set; }
        public Nullable<System.DateTime> Go_Live_Date__iMeet_ { get; set; }
        public string Complete_Duration__Formula_ { get; set; }
        public Nullable<double> C__Completed__iMeet_ { get; set; }
        public Nullable<double> C1stweek { get; set; }
        public Nullable<double> C2ndweek { get; set; }
        public Nullable<double> C3rdweek { get; set; }
        public Nullable<double> C4thweek { get; set; }
        public Nullable<double> C5thweek { get; set; }
        public Nullable<double> C6thweek { get; set; }
        public Nullable<double> C7thweek { get; set; }
        public Nullable<double> C8thweek { get; set; }
        public Nullable<double> C9thweek { get; set; }
        public Nullable<double> C10thweek { get; set; }
        public Nullable<double> C11thweek { get; set; }
        public Nullable<double> C12week { get; set; }
        public Nullable<double> c13thweek { get; set; }
        public Nullable<double> c14thweek { get; set; }
        public Nullable<double> c15thweek { get; set; }
        public Nullable<double> c16thweek { get; set; }
        public Nullable<double> c17thweek { get; set; }
        public Nullable<double> c18thweek { get; set; }
        public Nullable<double> c19thweek { get; set; }
        public Nullable<double> c20thweek { get; set; }
        public Nullable<double> c21thweek { get; set; }
        public Nullable<double> c22thweek { get; set; }
        public Nullable<double> c23thweek { get; set; }
        public Nullable<double> c24thweek { get; set; }
        public Nullable<int> Jan { get; set; }
        public Nullable<int> Feb { get; set; }
        public Nullable<int> Mar { get; set; }
        public Nullable<int> Apr { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> Jun { get; set; }
        public Nullable<int> Jul { get; set; }
        public Nullable<int> Aug { get; set; }
        public Nullable<int> Sep { get; set; }
        public Nullable<int> Oct { get; set; }
        public Nullable<int> Nov { get; set; }
        public Nullable<int> Dec { get; set; }
    }
}
