//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReportsAccess
    {
        public int AccessID { get; set; }
        public int UserID { get; set; }
        public string UID { get; set; }
        public bool IMPS { get; set; }
        public bool CTO { get; set; }
        public bool AutomatedCLR { get; set; }
        public bool StageGate { get; set; }
        public bool LessonsLearnt { get; set; }
        public bool CapacityTracker { get; set; }
        public bool CycleTime { get; set; }
        public bool ELTReport { get; set; }
        public bool C_Hierarchy { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string UserAccessStatus { get; set; }
        public bool ResourceUtilization { get; set; }
        public bool Prospect { get; set; }
        public Nullable<bool> MarketReport { get; set; }
        public Nullable<bool> CLREdits { get; set; }
        public Nullable<bool> MarketCommentsEdit { get; set; }
        public Nullable<bool> C_HierarchyEdits { get; set; }
        public Nullable<bool> NPS { get; set; }
        public Nullable<bool> NPSClientInfo { get; set; }
        public Nullable<bool> NPSAdmin { get; set; }
        public Nullable<bool> DigitalReport { get; set; }
        public Nullable<bool> NPSEdit { get; set; }
        public Nullable<bool> PerformanceAnalysis { get; set; }
    
        public virtual User User { get; set; }
    }
}
