//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wave
    {
        public int WaveID { get; set; }
        public Nullable<int> SCID { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string Scope { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Record_Status { get; set; }
        public string Waves { get; set; }
    
        public virtual SteeringCommittee SteeringCommittee { get; set; }
    }
}
