//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWTDashboardAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesterdayCLR
    {
        public int CLRID { get; set; }
        public string Client { get; set; }
        public double RevenueID { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public Nullable<double> RevenueVolumeUSD { get; set; }
        public Nullable<double> OppTOtalVolume { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string ProjectStatus { get; set; }
        public string ProjectLevel { get; set; }
        public Nullable<System.DateTime> ProjectStart_ForCycleTime { get; set; }
        public string GoLiveMonth { get; set; }
        public string GoLiveYear { get; set; }
        public string Status { get; set; }
        public string ImplementationType { get; set; }
        public string DataSourceType { get; set; }
        public string GlobalProjectManager { get; set; }
        public string RegionalProjectManager { get; set; }
        public string AssigneeFullName { get; set; }
        public string GlobalCISOBTLead { get; set; }
        public string GlobalCISHRFeedSpecialist { get; set; }
        public string GlobalCISPortraitLead { get; set; }
        public string RegionalCISOBTLead { get; set; }
        public string RegionalCISPortraitLead { get; set; }
        public string TaskRecordIdKey { get; set; }
        public string Sales_Stage_Name { get; set; }
    }
}
